# same as Linear Regression

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
ds = pd.read_excel('case_data.xlsx')
ds

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111

In [7]:
# check null values
ds.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [8]:
len(ds)

15

In [9]:
ds.shape

(15, 2)

In [10]:
# split them

In [11]:
x = ds['YearsExperience']
x.head()

0    1.1
1    1.3
2    1.5
3    2.0
4    2.2
Name: YearsExperience, dtype: float64

In [12]:
x.ndim

1

In [13]:
# convert 1d to 2d
x=x.values.reshape(-1,1)
x

array([[1.1],
       [1.3],
       [1.5],
       [2. ],
       [2.2],
       [2.9],
       [3. ],
       [3.2],
       [3.2],
       [3.7],
       [3.9],
       [4. ],
       [4. ],
       [4.1],
       [4.5]])

In [14]:
x.ndim

2

In [15]:
y = ds['Salary']
y.head()

0    39343
1    46205
2    37731
3    43525
4    39891
Name: Salary, dtype: int64

In [16]:
# data given to algorithm

In [17]:
import sklearn

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
# train the data

In [20]:
#x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
##Training_data = pd.DataFrame({'X_train':x_train.flatten(),'Y_train':y_train})
#Training_data

In [22]:
# test the data

In [23]:
#testing_data = pd.DataFrame({'X_test':x_test.flatten(),'Y_test':y_test})
#testing_data

In [24]:
# algorithm learn the data

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
reg = LinearRegression()

In [27]:
reg.fit(x,y)

LinearRegression()

In [28]:
reg.coef_

array([6853.4545736])

In [29]:
reg.intercept_

32537.528401176274

In [30]:
# SLR
# y = 8363.72180451 x + 26427.929197994992

In [31]:
# model make prediction

In [32]:
#y_train_predict = reg.predict(x_train)
#y_train_predict

In [33]:
y_test_predict = reg.predict(x)
y_test_predict

array([40076.32843213, 41447.01934685, 42817.71026157, 46244.43754837,
       47615.12846309, 52412.5466646 , 53097.89212196, 54468.58303668,
       54468.58303668, 57895.31032348, 59266.0012382 , 59951.34669556,
       59951.34669556, 60636.69215292, 63378.07398236])

In [34]:
res = pd.DataFrame({'actual':y,'prediction':y_test_predict})
res

actual    prediction
0    39343  40076.328432
1    46205  41447.019347
2    37731  42817.710262
3    43525  46244.437548
4    39891  47615.128463
5    56642  52412.546665
6    60150  53097.892122
7    54445  54468.583037
8    64445  54468.583037
9    57189  57895.310323
10   63218  59266.001238
11   55794  59951.346696
12   56957  59951.346696
13   57081  60636.692153
14   61111  63378.073982

In [35]:
#find the accuracy for this model [with best data 70%]

In [36]:
from sklearn.metrics import r2_score

In [37]:
#r2_score(y_train,y_train_predict)

In [38]:
# adjusted score

In [39]:
#1-(1-r2_score(y_train,y_train_predict))* (len(ds)-1) / (len(ds)-ds.shape[1]-1)

In [40]:
#find the accuracy for this model test

In [41]:
#y_test_predict = reg.predict(x_test)
#y_test_predict

In [42]:
r2_score(y,y_test_predict)

0.7020755183418668

In [43]:
# adjusted score
1-(1-r2_score(y,y_test_predict))* (len(ds)-1) / (len(ds)-ds.shape[1]-1)

0.6524214380655111

# add columns

In [45]:
ml = pd.read_csv("case2.csv")
ml

YearsExperience  Salary  Height
0               1.1   39343    1.47
1               1.3   46205    1.50
2               1.5   37731    1.52
3               2.0   43525    1.55
4               2.2   39891    1.57
5               2.9   56642    1.60
6               3.0   60150    1.63
7               3.2   54445    1.65
8               3.2   64445    1.68
9               3.7   57189    1.70
10              3.9   63218    1.73
11              4.0   55794    1.75
12              4.0   56957    1.78
13              4.1   57081    1.80
14              4.5   61111    1.83

In [46]:
# check null values
ml.isnull().sum()

YearsExperience    0
Salary             0
Height             0
dtype: int64

In [47]:
ml.shape

(15, 3)

In [52]:
# split them
x1 = ml.drop(['Salary'],axis =1)
x1.head()

YearsExperience  Height
0              1.1    1.47
1              1.3    1.50
2              1.5    1.52
3              2.0    1.55
4              2.2    1.57

In [53]:
x1.shape

(15, 2)

In [54]:
y1 = ml['Salary']
y1.head()

0    39343
1    46205
2    37731
3    43525
4    39891
Name: Salary, dtype: int64

In [55]:
y1.shape

(15,)

In [60]:
import sklearn

In [57]:
from sklearn.model_selection import train_test_split

In [61]:
from sklearn.linear_model import LinearRegression

In [62]:
reg = LinearRegression()

In [63]:
reg.fit(x1,y1)

LinearRegression()

In [64]:
reg.coef_

array([ 14644.63233411, -77180.11347421])

In [65]:
reg.intercept_

136770.40050132203

In [66]:
y1_test_predict = reg.predict(x1)
y1_test_predict

array([39424.72926177, 40038.25232436, 41423.5765217 , 46430.48928453,
       47815.81348187, 55751.65271152, 54900.71254071, 56286.03673805,
       53970.63333382, 59749.3472314 , 60362.87029399, 60283.73125792,
       57968.32785369, 57889.18881762, 61431.63834704])

In [67]:
res = pd.DataFrame({'actual':y1,'prediction':y1_test_predict})
res

actual    prediction
0    39343  39424.729262
1    46205  40038.252324
2    37731  41423.576522
3    43525  46430.489285
4    39891  47815.813482
5    56642  55751.652712
6    60150  54900.712541
7    54445  56286.036738
8    64445  53970.633334
9    57189  59749.347231
10   63218  60362.870294
11   55794  60283.731258
12   56957  57968.327854
13   57081  57889.188818
14   61111  61431.638347

In [68]:
from sklearn.metrics import r2_score

In [69]:
r2_score(y1,y1_test_predict)

0.7388592596500807

In [71]:
ml.shape[1]

3

In [72]:
# adjusted score
1-(1-r2_score(y1,y1_test_predict)) * (len(ml)-1) / (len(ml) - ml.shape[1] -1)

0.6676390577364664

# old column - new column

In [73]:
0.6676390577364664-0.6524214380655111

0.015217619670955251