In [121]:
import sklearn

In [122]:
from sklearn.datasets import load_boston

In [123]:
a = load_boston()
a

C:\Users\91893\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [124]:
dir(data)

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'target']

In [125]:
# lets check them ['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'target']

In [126]:
a.data # english words

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [127]:
a.DESCR #dependent variable

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [128]:
a.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [129]:
import numpy as np
import pandas as pd

In [130]:
df = pd.DataFrame(data = a.data,columns =a.feature_names)
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [131]:
df['dependent'] =a.target
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  dependent  
0       15.3  396.90   4.98       24.0  
1       17.8  396.90   9.14       21.6  
2       17.8  392.83   4.03       34.7  
3       18.7  394.63   2.94       33.4  
4       18.7  396.90   5.33       36.2  
..       ...     ...    ...        ...  
501     21.0  391.99   9.67       22.4  
502     21.0  396.90   9.08       20.6  
503     21.0  396.90   5.64       23.9  
504     21.0  393.45   6.48       22.0  
505     21.0  396.90   7.88       11.9  

[506 rows x 14 columns]

In [132]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  dependent  
0     15.3  396.90   4.98       24.0  
1     17.8  396.90   9.14       21.6  
2     17.8  392.83   4.03       34.7  
3     18.7  394.63   2.94       33.4  
4     18.7  396.90   5.33       36.2

In [133]:
df.shape

(506, 14)

In [134]:
x = df.iloc[:,:-1]
x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [135]:
y = df.iloc[:,-1]
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: dependent, Length: 506, dtype: float64

In [136]:
from sklearn.model_selection import train_test_split

In [137]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=12)

In [138]:
from sklearn.linear_model import LinearRegression

In [139]:
reg = LinearRegression()

In [140]:
# inference the data

In [141]:
reg.fit(X_train,y_train)

LinearRegression()

In [142]:
#y_train_predict = reg.predict(_train)
#y_train_predict

In [143]:
y_test.head()

334    20.7
394    12.7
404     8.5
236    25.1
307    28.2
Name: dependent, dtype: float64

In [144]:
y_test_predict =reg.predict(X_test)
y_test_predict

array([21.91255819, 18.30810393,  7.50219553, 30.56672721, 32.91643787,
       21.94506783, 19.99354229, 38.53691423, 33.08257927, 25.81375883,
       23.46271388, 22.22333412, 20.92957888, 22.73842166, 33.89928547,
       44.23017329, 20.26969686, 28.70546941, 23.39077081, 27.30953472,
       33.65993455, 13.74412782, 22.85303137, 13.47672519, 25.25017965,
       20.94769522, 20.73843388, 14.75829569, 25.85477102, 37.8966851 ,
       25.91678085, 27.90561874, 17.35808281, 32.57124994, 42.70662575,
       18.06106107, 21.58673586, 40.23534211, 14.09071159, 25.34508199,
       17.88351719, 24.77714991, 21.44933437, 33.97806095, 18.94344894,
       18.35995674, 20.35797486, 14.9675233 , 37.10757255, 24.09449339,
       25.37414394, 20.37939401, 16.37921593, 25.12324164, 18.4736912 ,
       17.6412831 , 22.90424687, 20.13733519, 20.15462786, 20.60757164,
       20.04302053, 30.09748267, 22.63438137, 18.34893258, 17.96705901,
       25.91925083, 27.23549675, 13.14310717, 24.01906978, 39.99

In [145]:
from sklearn.metrics import r2_score

In [146]:
print(f'the model accuracy :{r2_score(y_test,y_test_predict)}')

the model accuracy :0.7484031678924543


In [89]:
# creating columns and linear model of m value

In [90]:
performance = pd.DataFrame()
performance['columns_names']=x_train.columns

In [91]:
performance

columns_names
0           CRIM
1             ZN
2          INDUS
3           CHAS
4            NOX
5             RM
6            AGE
7            DIS
8            RAD
9            TAX
10       PTRATIO
11             B
12         LSTAT

In [92]:
performance['linear_model_coeff']=reg.coef_

In [93]:
performance

columns_names  linear_model_coeff
0           CRIM           -0.113056
1             ZN            0.030110
2          INDUS            0.040381
3           CHAS            2.784438
4            NOX          -17.202633
5             RM            4.438835
6            AGE           -0.006296
7            DIS           -1.447865
8            RAD            0.262430
9            TAX           -0.010647
10       PTRATIO           -0.915456
11             B            0.012351
12         LSTAT           -0.508571

In [95]:
x_train['AGE']

477    97.3
15     56.5
332    23.3
423    85.1
19     69.5
       ... 
106    91.9
270    42.1
348    29.7
435    94.6
102    85.4
Name: AGE, Length: 404, dtype: float64

# ridge

In [147]:
from sklearn.linear_model import Ridge

In [148]:
ridge_reg = Ridge(alpha=0.3)

In [149]:
ridge_reg .fit(X_train,y_train)

Ridge(alpha=0.3)

In [150]:
y_test_predict =ridge_reg.predict(X_test)
y_test_predict

array([22.26433344, 18.40471542,  7.58152227, 30.42642282, 32.85162886,
       21.86109827, 20.15281972, 38.68363985, 33.14931015, 25.83764878,
       23.47521558, 22.22704374, 20.86083631, 22.72172268, 33.80219929,
       44.07596932, 20.57269881, 28.57379092, 23.75263132, 26.99729105,
       33.42847019, 13.82152928, 22.80501482, 13.65474688, 25.39222728,
       20.76652809, 20.63391013, 14.42144357, 25.87658271, 37.80020019,
       25.96205417, 27.83877861, 17.50118289, 32.45483019, 42.97614792,
       18.11906601, 21.55288635, 40.18617347, 14.75779048, 25.23965145,
       17.72166794, 24.84397613, 21.27224094, 34.09061596, 18.76195593,
       18.45436287, 20.52643061, 15.1510823 , 36.98324555, 23.78346055,
       26.13831932, 21.10012093, 16.09476549, 25.18965569, 18.5217804 ,
       17.69270746, 23.09788214, 20.16899827, 19.81693508, 20.68557838,
       20.21170159, 30.13361756, 22.4333215 , 18.38421418, 18.66297446,
       25.79726678, 27.07875316, 13.28743761, 23.99490849, 40.07

In [151]:
from sklearn.metrics import r2_score

In [160]:
print(f'the model accuracy :{r2_score(y_test,y_test_predict)}')

the model accuracy :0.7217941543928879


In [154]:
performance = pd.DataFrame()
performance['columns_names']=x_train.columns
performance['linear_model_coeff']=reg.coef_
performance['ridge_model_coeff']=ridge_reg.coef_
performance

columns_names  linear_model_coeff  ridge_model_coeff
0           CRIM           -0.098652          -0.096736
1             ZN            0.046743           0.047368
2          INDUS            0.030359           0.014935
3           CHAS            3.016142           2.949943
4            NOX          -18.118639         -14.503203
5             RM            3.733258           3.750750
6            AGE            0.014699           0.011927
7            DIS           -1.377569          -1.328577
8            RAD            0.324386           0.315007
9            TAX           -0.013555          -0.013781
10       PTRATIO           -0.820106          -0.782316
11             B            0.009096           0.009352
12         LSTAT           -0.561055          -0.566945

# lasso

In [155]:
from sklearn.linear_model import Lasso

In [157]:
lasso_reg = Lasso(alpha=0.3)

In [158]:
lasso_reg.fit(X_train,y_train)

Lasso(alpha=0.3)

In [159]:
y_test_predict =lasso_reg.predict(X_test)
y_test_predict

array([24.27511048, 19.19532104,  7.77944742, 27.38997874, 32.41842957,
       21.60112366, 21.49554219, 38.75264176, 32.72203262, 26.33509724,
       23.21866165, 22.4935861 , 21.09437296, 23.35466809, 33.42648693,
       39.78727964, 19.18011303, 28.31608462, 22.72571992, 26.49139759,
       29.66125558, 14.22136948, 23.20044308, 13.69392878, 26.2612345 ,
       21.16033285, 20.80014388, 13.59115597, 26.64574284, 36.81783924,
       25.91436977, 27.72132824, 18.0187017 , 31.86649693, 42.49343966,
       18.05643076, 22.34863474, 39.02153107, 17.9446213 , 25.42987766,
       17.51491791, 25.51269627, 20.92907664, 34.20410297, 18.81107333,
       19.18440485, 21.43863113, 19.02083557, 36.35737716, 23.39803561,
       30.08332297, 24.6353687 , 15.21216085, 25.87765092, 18.35944613,
       18.04311186, 24.65218177, 20.50568734, 17.81224353, 20.82435711,
       21.01105964, 30.06767256, 21.57616601, 18.99677765, 22.86060078,
       25.67344154, 27.12955751, 14.28778147, 24.44265959, 38.84

In [161]:
from sklearn.metrics import r2_score

In [162]:
print(f'the model accuracy :{r2_score(y_test,y_test_predict)}')

the model accuracy :0.7217941543928879


In [163]:
performance = pd.DataFrame()
performance['columns_names']=x_train.columns
performance['linear_model_coeff']=reg.coef_
performance['ridge_model_coeff']=ridge_reg.coef_
performance['lasso_model_coeff']=lasso_reg.coef_
performance

columns_names  linear_model_coeff  ridge_model_coeff  lasso_model_coeff
0           CRIM           -0.098652          -0.096736          -0.084109
1             ZN            0.046743           0.047368           0.048755
2          INDUS            0.030359           0.014935          -0.000189
3           CHAS            3.016142           2.949943           0.000000
4            NOX          -18.118639         -14.503203          -0.000000
5             RM            3.733258           3.750750           2.905206
6            AGE            0.014699           0.011927           0.012658
7            DIS           -1.377569          -1.328577          -0.977602
8            RAD            0.324386           0.315007           0.297381
9            TAX           -0.013555          -0.013781          -0.016522
10       PTRATIO           -0.820106          -0.782316          -0.657792
11             B            0.009096           0.009352           0.009993
12         LSTAT           -0.561055          -0.566945          -0.670121